TERM2GREYNIR_POS = {'n': ['no'],                           
             'g': ['gr'],                           
             'x': [],                               
             'e': [],                               
             'v': ['tölvupóstfang'],
             'l': ['lo'],                           
             'fa': ['fn'], 
             'fb': ['fn'],  
             'fe': ['fn'],     
             'fo': ['fn'],  
             'fp': ['pfn'], 
             'fs': ['fn'], 
             'ft': ['fn'], 
             'tf': ['to', 'tala'],
             'ta': ['töl', 'ártal'],
             'tp': ['to', 'prósenta'],
             'to': ['to', 'raðnr'],
             'sn': ['so', 'nh'],
             'sb': ['so', 'bh'],
             'sf': ['so', 'fh'],
             'sv': ['so', 'vh'],
             'ss': ['so'], 
             'sl': ['so', 'lhnt'],
             'sþ': ['so', 'lhþt'],
             'cn': ['st'],
             'ct': ['st'],
             'c': ['st'],
             'aa': ['ao'],
             'af': ['ao'],
             'au': ['uh'],
             'ao': [],
             'aþ': [],
             'ae': [],
             'as': [],
             'ks': [],
             'kt': [],
             'p': ['grm'],
             'pl': ['grm'],
             'pk': ['grm'],
             'pg': ['grm'],
             'pa': ['grm'],
             'ns': [],
             'm': [],
             'masc': ['kk'],
             'fem': ['kvk'],
             'neut': ['hk'],
             'gender_x': [],
             '1': ['p1'],
             '2': ['p2'],
             '3': ['p3'],
             'sing': ['et'],
             'plur': ['ft'],
             'nom': ['nf'],
             'acc': ['þf'],
             'dat': ['þgf'],
             'gen': ['ef'],
             'definite': [],
             'proper': ['', '?'],
             'strong': ['sb'],
             'weak': ['vb'],
             'equiinflected': [],
             'pos': [],
             'cmp': ['mst'],
             'superl': ['esb'],
             'past': ['þt'],
             'pres': ['nt'],
             'pass': [],
             'act': [],
             'mid': ['mm']
}
